openapi: 3.1.0
info:
  title: Terms API
  version: 1.0.0

paths:
  /terms:
    get:
      operationId: getTerms
      parameters:
        - name: query
          in: query
          style: form
          explode: true
          required: false  # Query optional
          schema:
            $ref: './schemas/termQuery.json'
      responses:
        "200":
          description: array of term objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/term.json"
s